# Generated by Django 5.2.18 on 2026-10-07 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('garage', '0001_initial'),
        ('geo', '0001_initial'),
        ('loads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('comment_only', 'Comment Only'), ('price_bid', 'Price Bid')], default='price_bid', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('countered', 'Countered')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_as_carrier', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.currency')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='loads.load')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counters', to='offers.offer')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_proposed', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_received', to=settings.AUTH_USER_MODEL)),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='garage.vehicle')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='garage.vehicle')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('load', 'carrier'), name='unique_pending_offer_per_carrier_load'), models.CheckConstraint(condition=models.Q(('proposer', models.F('recipient')), _negated=True), name='check_offer_proposer_not_recipient'), models.CheckConstraint(condition=models.Q(models.Q(('mode', 'price_bid'), _negated=True), ('amount__isnull', False), _connector='OR'), name='check_offer_price_bid_requires_amount')],
            },
        ),
    ]
