# Generated by Django 5.2.18 on 2026-10-07 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name_i18n', models.JSONField(default=dict)),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('kind', models.CharField(choices=[('tractor', 'Tractor'), ('trailer', 'Trailer')], max_length=20)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('tractor', 'Tractor'), ('trailer', 'Trailer')], max_length=20)),
                ('plate_number', models.CharField(max_length=50, unique=True)),
                ('tech_passport_no', models.CharField(blank=True, default='', max_length=50)),
                ('owner_full_name', models.CharField(blank=True, default='', max_length=255)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('tech_passport_image', models.ImageField(blank=True, null=True, upload_to='vehicles/tech_passports/')),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
                ('paired_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_vehicles', to='garage.vehicle')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='garage.vehicletype')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-id'],
            },
        ),
    ]
