# Generated by Django 5.2.18 on 2026-10-07 19:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_company_device_otpcode'),
        ('garage', '0001_initial'),
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo_description', models.CharField(max_length=255)),
                ('cargo_type', models.CharField(blank=True, default='', max_length=100)),
                ('weight_t', models.DecimalField(decimal_places=3, max_digits=10)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('packaging', models.CharField(blank=True, default='', max_length=100)),
                ('transport_mode', models.CharField(choices=[('FTL', 'FTL'), ('LTL', 'LTL')], default='FTL', max_length=10)),
                ('vehicle_category', models.CharField(blank=True, default='', max_length=100)),
                ('trucks_needed', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('trucks_found', models.PositiveIntegerField(default=0)),
                ('is_adr', models.BooleanField(default=False)),
                ('adr_class', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('temp_controlled', models.BooleanField(default=False)),
                ('temp_min_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temp_max_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('vat_included', models.BooleanField(default=False)),
                ('price_negotiable', models.BooleanField(default=True)),
                ('distance_km', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('body_types', models.ManyToManyField(blank=True, related_name='loads', to='garage.vehicletype')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='accounts.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loads', to='geo.currency')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Load',
                'verbose_name_plural': 'Loads',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('load', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payment_terms', serialize=False, to='loads.load')),
                ('prepay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('prepay_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('transfer', 'Transfer')], default='', max_length=20)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('paid_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('transfer', 'Transfer')], default='', max_length=20)),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('payment_due_days', models.PositiveIntegerField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Payment Terms',
                'verbose_name_plural': 'Payment Terms',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_loads', to=settings.AUTH_USER_MODEL)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='loads.load')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='loads/documents/')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='loads.load')),
            ],
            options={
                'verbose_name': 'Load Document',
                'verbose_name_plural': 'Load Documents',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seq', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('loading', 'Loading'), ('stop', 'Stop'), ('transit', 'Transit'), ('border', 'Border'), ('customs', 'Customs'), ('unloading', 'Unloading')], max_length=20)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('planned_from', models.DateTimeField(blank=True, null=True)),
                ('planned_to', models.DateTimeField(blank=True, null=True)),
                ('asap', models.BooleanField(default=False)),
                ('ready_to_load', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, default='')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_points', to='geo.country')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='loads.load')),
            ],
            options={
                'verbose_name': 'Route Point',
                'verbose_name_plural': 'Route Points',
                'ordering': ['seq'],
            },
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['status', '-published_at'], name='load_status_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['shipper'], name='load_shipper_idx'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['currency'], name='load_currency_idx'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'load'), name='unique_user_favorite_load'),
        ),
        migrations.AddConstraint(
            model_name='routepoint',
            constraint=models.UniqueConstraint(fields=('load', 'seq'), name='unique_route_point_load_seq'),
        ),
    ]
