# Generated by Django 5.2.18 on 2026-10-07 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name_i18n', models.JSONField(default=dict)),
                ('flag_url', models.URLField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('fetched_at', models.DateTimeField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_exchange_rates', to='geo.currency')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_exchange_rates', to='geo.currency')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['base', 'quote', '-fetched_at'], name='geo_rate_latest_idx')],
                'constraints': [models.UniqueConstraint(fields=('base', 'quote', 'fetched_at'), name='unique_base_quote_fetched_at')],
            },
        ),
    ]
